from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field


class CorrectionEntry(BaseModel):
    claim: str = Field(description="The original unsupported claim")
    reason: str = Field(description="Why it was flagged")
    corrected: str = Field(description="The corrected or struck version")
    source: str = Field(description="Source that contradicted or failed to support the claim")


class ResearchState(BaseModel):
    topic: str = Field(description="The user-provided research topic")
    sub_questions: List[str] = Field(default_factory=list, description="Sub-questions generated by the planner")
    outline: str = Field(default="", description="Report outline from the planner")
    search_results: List[dict] = Field(default_factory=list, description="Raw search results")
    summaries: str = Field(default="", description="Grounded per-sub-question summaries")
    fact_check_verdicts: List[dict] = Field(default_factory=list, description="Structured JSON verdicts")
    correction_log: List[CorrectionEntry] = Field(default_factory=list, description="What was corrected and why")
    final_report: str = Field(default="", description="The final markdown report")
    current_stage: str = Field(default="", description="Current pipeline stage for UI progress")
